// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module solve_NTRU_zint_bezout_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        vla1_address0,
        vla1_ce0,
        vla1_we0,
        vla1_d0,
        vla1_q0,
        vla1_address1,
        vla1_ce1,
        vla1_we1,
        vla1_d1,
        vla1_q1,
        ap_return
);

parameter    ap_ST_fsm_state1 = 34'd1;
parameter    ap_ST_fsm_state2 = 34'd2;
parameter    ap_ST_fsm_state3 = 34'd4;
parameter    ap_ST_fsm_state4 = 34'd8;
parameter    ap_ST_fsm_state5 = 34'd16;
parameter    ap_ST_fsm_state6 = 34'd32;
parameter    ap_ST_fsm_state7 = 34'd64;
parameter    ap_ST_fsm_state8 = 34'd128;
parameter    ap_ST_fsm_state9 = 34'd256;
parameter    ap_ST_fsm_state10 = 34'd512;
parameter    ap_ST_fsm_state11 = 34'd1024;
parameter    ap_ST_fsm_state12 = 34'd2048;
parameter    ap_ST_fsm_state13 = 34'd4096;
parameter    ap_ST_fsm_state14 = 34'd8192;
parameter    ap_ST_fsm_state15 = 34'd16384;
parameter    ap_ST_fsm_state16 = 34'd32768;
parameter    ap_ST_fsm_state17 = 34'd65536;
parameter    ap_ST_fsm_state18 = 34'd131072;
parameter    ap_ST_fsm_state19 = 34'd262144;
parameter    ap_ST_fsm_state20 = 34'd524288;
parameter    ap_ST_fsm_state21 = 34'd1048576;
parameter    ap_ST_fsm_state22 = 34'd2097152;
parameter    ap_ST_fsm_state23 = 34'd4194304;
parameter    ap_ST_fsm_state24 = 34'd8388608;
parameter    ap_ST_fsm_state25 = 34'd16777216;
parameter    ap_ST_fsm_state26 = 34'd33554432;
parameter    ap_ST_fsm_state27 = 34'd67108864;
parameter    ap_ST_fsm_state28 = 34'd134217728;
parameter    ap_ST_fsm_state29 = 34'd268435456;
parameter    ap_ST_fsm_state30 = 34'd536870912;
parameter    ap_ST_fsm_state31 = 34'd1073741824;
parameter    ap_ST_fsm_state32 = 34'd2147483648;
parameter    ap_ST_fsm_state33 = 34'd4294967296;
parameter    ap_ST_fsm_state34 = 34'd8589934592;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] vla1_address0;
output   vla1_ce0;
output  [3:0] vla1_we0;
output  [31:0] vla1_d0;
input  [31:0] vla1_q0;
output  [11:0] vla1_address1;
output   vla1_ce1;
output  [3:0] vla1_we1;
output  [31:0] vla1_d1;
input  [31:0] vla1_q1;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[11:0] vla1_address0;
reg vla1_ce0;
reg[3:0] vla1_we0;
reg[31:0] vla1_d0;
reg[11:0] vla1_address1;
reg vla1_ce1;
reg[3:0] vla1_we1;
reg[31:0] vla1_d1;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [33:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [11:0] vla1_addr_reg_2660;
wire   [11:0] vla1_addr_28_reg_2665;
wire  signed [30:0] trunc_ln651_fu_702_p1;
reg  signed [30:0] trunc_ln651_reg_2670;
wire    ap_CS_fsm_state2;
wire  signed [30:0] y_7_fu_742_p2;
reg  signed [30:0] y_7_reg_2676;
wire  signed [30:0] trunc_ln651_1_fu_748_p1;
reg  signed [30:0] trunc_ln651_1_reg_2682;
wire  signed [30:0] y_11_fu_770_p2;
reg  signed [30:0] y_11_reg_2689;
wire   [30:0] mul_ln658_fu_776_p2;
reg   [30:0] mul_ln658_reg_2695;
wire    ap_CS_fsm_state3;
wire  signed [30:0] y_12_fu_790_p2;
reg  signed [30:0] y_12_reg_2700;
wire   [30:0] mul_ln658_2_fu_795_p2;
reg   [30:0] mul_ln658_2_reg_2705;
wire   [8:0] tmp_fu_803_p3;
reg   [8:0] tmp_reg_2713;
wire    ap_CS_fsm_state4;
wire  signed [30:0] sub_ln658_1_fu_880_p2;
reg  signed [30:0] sub_ln658_1_reg_2733;
wire    ap_CS_fsm_state5;
wire   [0:0] exitcond97_fu_865_p2;
wire  signed [30:0] y_15_fu_885_p2;
reg  signed [30:0] y_15_reg_2738;
wire   [30:0] mul_ln659_fu_890_p2;
reg   [30:0] mul_ln659_reg_2743;
wire   [8:0] tmp_3_fu_903_p3;
reg   [8:0] tmp_3_reg_2751;
wire    ap_CS_fsm_state6;
wire  signed [30:0] y_17_fu_975_p2;
reg  signed [30:0] y_17_reg_2771;
wire    ap_CS_fsm_state7;
wire   [0:0] exitcond96_fu_965_p2;
wire  signed [30:0] sub_ln659_fu_984_p2;
reg  signed [30:0] sub_ln659_reg_2777;
wire    ap_CS_fsm_state8;
wire  signed [30:0] sub_ln659_1_fu_993_p2;
reg  signed [30:0] sub_ln659_1_reg_2782;
wire   [30:0] x0i_fu_1087_p2;
reg   [30:0] x0i_reg_2807;
wire    ap_CS_fsm_state10;
wire   [0:0] exitcond94_fu_1071_p2;
wire   [8:0] tmp_8_fu_1100_p3;
reg   [8:0] tmp_8_reg_2815;
wire    ap_CS_fsm_state11;
wire   [30:0] y0i_fu_1177_p2;
reg   [30:0] y0i_reg_2835;
wire    ap_CS_fsm_state12;
wire   [0:0] exitcond93_fu_1162_p2;
wire   [8:0] tmp_10_fu_1190_p3;
reg   [8:0] tmp_10_reg_2843;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state18;
wire   [31:0] a0_1_fu_1354_p2;
wire    ap_CS_fsm_state19;
wire   [31:0] a1_1_fu_1372_p2;
wire   [31:0] b0_1_fu_1390_p2;
wire   [31:0] b1_1_fu_1408_p2;
wire   [31:0] c0_fu_1448_p2;
wire   [6:0] j_5_fu_1454_p2;
wire   [63:0] a_hi_fu_1524_p2;
reg   [63:0] a_hi_reg_2952;
wire   [0:0] icmp_ln2143_fu_1460_p2;
wire   [63:0] b_hi_fu_1546_p2;
reg   [63:0] b_hi_reg_2957;
wire    ap_CS_fsm_state20;
wire   [4:0] i_1_fu_1562_p2;
wire    ap_CS_fsm_state21;
wire   [31:0] a_lo_3_fu_1822_p2;
wire   [0:0] icmp_ln2184_fu_1556_p2;
wire   [63:0] pa_2_fu_1842_p2;
wire   [63:0] pb_2_fu_1854_p2;
wire   [63:0] a_hi_3_fu_1894_p2;
wire   [31:0] b_lo_3_fu_1914_p2;
wire   [63:0] qa_2_fu_1926_p2;
wire   [63:0] qb_2_fu_1938_p2;
wire   [63:0] b_hi_3_fu_1970_p2;
wire   [6:0] u_34_fu_1982_p2;
reg   [6:0] u_34_reg_3023;
wire    ap_CS_fsm_state22;
wire   [11:0] zext_ln1830_1_fu_1996_p1;
reg   [11:0] zext_ln1830_1_reg_3028;
wire   [0:0] icmp_ln1826_fu_1976_p2;
wire   [0:0] icmp_ln1834_fu_2042_p2;
reg   [0:0] icmp_ln1834_reg_3044;
wire   [0:0] nega_fu_2058_p3;
reg   [0:0] nega_reg_3048;
wire   [31:0] select_ln1784_fu_2066_p3;
reg   [31:0] select_ln1784_reg_3054;
wire   [30:0] select_ln1797_fu_2074_p3;
reg   [30:0] select_ln1797_reg_3059;
wire    ap_CS_fsm_state23;
wire   [6:0] u_33_fu_2230_p2;
reg   [6:0] u_33_reg_3077;
wire    ap_CS_fsm_state24;
reg   [11:0] vla1_addr_52_reg_3082;
wire   [0:0] icmp_ln1793_fu_2224_p2;
wire   [0:0] negb_fu_2269_p3;
reg   [0:0] negb_reg_3088;
wire   [31:0] select_ln1784_1_fu_2277_p3;
reg   [31:0] select_ln1784_1_reg_3094;
wire   [30:0] select_ln1797_1_fu_2285_p3;
reg   [30:0] select_ln1797_1_reg_3099;
wire    ap_CS_fsm_state25;
wire   [6:0] u_35_fu_2346_p2;
reg   [6:0] u_35_reg_3112;
wire    ap_CS_fsm_state26;
reg   [11:0] vla1_addr_53_reg_3117;
wire   [0:0] icmp_ln1793_1_fu_2340_p2;
wire   [63:0] pa_3_fu_2404_p2;
reg   [63:0] pa_3_reg_3123;
wire   [63:0] pb_3_fu_2423_p2;
reg   [63:0] pb_3_reg_3128;
wire   [63:0] qa_3_fu_2449_p2;
reg   [63:0] qa_3_reg_3133;
wire   [63:0] qb_3_fu_2468_p2;
reg   [63:0] qb_3_reg_3138;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state32;
wire   [0:0] icmp_ln2270_fu_2546_p2;
wire    grp_zint_co_reduce_mod_1_fu_674_ap_start;
wire    grp_zint_co_reduce_mod_1_fu_674_ap_done;
wire    grp_zint_co_reduce_mod_1_fu_674_ap_idle;
wire    grp_zint_co_reduce_mod_1_fu_674_ap_ready;
wire   [11:0] grp_zint_co_reduce_mod_1_fu_674_vla1_address0;
wire    grp_zint_co_reduce_mod_1_fu_674_vla1_ce0;
wire   [3:0] grp_zint_co_reduce_mod_1_fu_674_vla1_we0;
wire   [31:0] grp_zint_co_reduce_mod_1_fu_674_vla1_d0;
wire   [11:0] grp_zint_co_reduce_mod_1_fu_674_vla1_address1;
wire    grp_zint_co_reduce_mod_1_fu_674_vla1_ce1;
wire   [3:0] grp_zint_co_reduce_mod_1_fu_674_vla1_we1;
wire   [31:0] grp_zint_co_reduce_mod_1_fu_674_vla1_d1;
reg   [7:0] grp_zint_co_reduce_mod_1_fu_674_a;
reg   [11:0] grp_zint_co_reduce_mod_1_fu_674_b;
reg   [10:0] grp_zint_co_reduce_mod_1_fu_674_m;
reg   [30:0] grp_zint_co_reduce_mod_1_fu_674_m0i;
reg   [6:0] j_reg_410;
wire    ap_CS_fsm_state17;
wire   [0:0] icmp_ln2120_fu_1277_p2;
reg   [6:0] j_1_reg_421;
reg   [31:0] b1_reg_434;
reg   [31:0] b0_reg_445;
reg   [31:0] a1_reg_456;
reg   [31:0] a0_reg_467;
reg   [31:0] c1_reg_478;
reg   [31:0] c0_2_reg_489;
reg   [4:0] i_reg_502;
reg  signed [63:0] qb_reg_513;
reg  signed [63:0] qa_reg_525;
reg  signed [63:0] pb_reg_537;
reg  signed [63:0] pa_reg_549;
reg   [31:0] b_lo_1_reg_561;
reg   [31:0] a_lo_1_reg_570;
reg   [63:0] b_hi_1_reg_579;
reg   [63:0] a_hi_1_reg_588;
reg  signed [32:0] ccb_reg_597;
reg  signed [32:0] cca_reg_609;
reg   [6:0] u_reg_621;
reg   [0:0] cc_reg_632;
reg   [6:0] u_20_reg_642;
reg   [0:0] cc_12_reg_653;
reg   [6:0] u_23_reg_663;
reg    grp_zint_co_reduce_mod_1_fu_674_ap_start_reg;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state30;
wire   [63:0] p_cast9_fu_831_p1;
wire   [63:0] p_cast10_fu_855_p1;
wire   [63:0] p_cast11_fu_931_p1;
wire   [63:0] p_cast12_fu_955_p1;
wire   [63:0] p_cast13_fu_1036_p1;
wire    ap_CS_fsm_state9;
wire   [63:0] p_cast14_fu_1060_p1;
wire   [63:0] p_cast15_fu_1128_p1;
wire   [63:0] p_cast16_fu_1152_p1;
wire   [63:0] p_cast17_fu_1218_p1;
wire   [63:0] p_cast18_fu_1242_p1;
wire    ap_CS_fsm_state14;
wire   [63:0] zext_ln2146_fu_1316_p1;
wire   [63:0] zext_ln2147_fu_1337_p1;
wire   [63:0] zext_ln1830_fu_2016_p1;
wire   [63:0] zext_ln1831_fu_2037_p1;
wire   [63:0] zext_ln1835_fu_2170_p1;
wire   [63:0] zext_ln1836_fu_2199_p1;
wire   [63:0] zext_ln1796_fu_2264_p1;
wire   [63:0] zext_ln1796_1_fu_2380_p1;
wire   [63:0] zext_ln2271_fu_2580_p1;
reg   [6:0] loop_index26_fu_154;
wire   [6:0] empty_159_fu_860_p2;
reg   [6:0] loop_index20_fu_158;
wire   [6:0] empty_162_fu_960_p2;
reg   [6:0] empty_172_fu_162;
wire   [6:0] add_ptr7_sum_fu_1002_p2;
wire   [0:0] exitcond95_fu_1041_p2;
reg   [6:0] empty_164_fu_166;
wire   [6:0] empty_165_fu_1065_p2;
reg   [6:0] loop_index14_fu_170;
wire   [6:0] empty_168_fu_1157_p2;
reg   [6:0] loop_index_fu_174;
wire   [6:0] empty_171_fu_1247_p2;
wire   [0:0] exitcond92_fu_1252_p2;
reg   [12:0] num_fu_178;
wire   [12:0] num_3_fu_2475_p2;
reg   [6:0] j_3_fu_182;
wire   [6:0] j_7_fu_2585_p2;
reg   [31:0] rc_1_fu_186;
wire   [31:0] rc_2_fu_2596_p2;
wire   [31:0] rc_fu_2532_p2;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state34;
wire   [31:0] add_ln2114_fu_1267_p2;
wire   [31:0] trunc_ln1841_fu_2048_p1;
wire   [31:0] trunc_ln1842_fu_2053_p1;
wire   [31:0] zext_ln1835_1_fu_2150_p1;
wire   [31:0] zext_ln1836_1_fu_2179_p1;
wire   [31:0] zext_ln1798_fu_2327_p1;
wire   [31:0] zext_ln1798_1_fu_2519_p1;
wire  signed [30:0] y_fu_706_p2;
wire   [30:0] mul_ln656_fu_712_p2;
wire  signed [30:0] y_6_fu_724_p0;
wire  signed [30:0] y_6_fu_724_p2;
wire   [30:0] mul_ln657_fu_730_p2;
wire  signed [30:0] y_7_fu_742_p0;
wire  signed [30:0] y_10_fu_752_p2;
wire   [30:0] mul_ln656_3_fu_758_p2;
wire  signed [30:0] y_11_fu_770_p0;
wire   [30:0] mul_ln657_3_fu_780_p2;
wire  signed [30:0] y_12_fu_790_p0;
wire   [10:0] p_cast_fu_811_p1;
wire   [10:0] empty_fu_815_p2;
wire   [8:0] tmp_1_fu_821_p4;
wire   [11:0] p_cast1_fu_836_p1;
wire   [11:0] empty_158_fu_839_p2;
wire   [9:0] tmp_2_fu_845_p4;
wire  signed [30:0] y_15_fu_885_p0;
wire   [10:0] p_cast2_fu_911_p1;
wire   [10:0] empty_160_fu_915_p2;
wire   [8:0] tmp_4_fu_921_p4;
wire   [11:0] p_cast3_fu_936_p1;
wire   [11:0] empty_161_fu_939_p2;
wire   [9:0] tmp_5_fu_945_p4;
wire   [30:0] mul_ln659_1_fu_989_p2;
wire   [8:0] tmp_6_fu_1008_p3;
wire   [9:0] p_cast4_fu_1016_p1;
wire   [9:0] empty_163_fu_1020_p2;
wire   [7:0] tmp_7_fu_1026_p4;
wire  signed [30:0] x0i_fu_1087_p1;
wire   [10:0] p_cast5_fu_1108_p1;
wire   [10:0] empty_166_fu_1112_p2;
wire   [8:0] tmp_9_fu_1118_p4;
wire   [11:0] p_cast6_fu_1133_p1;
wire   [11:0] empty_167_fu_1136_p2;
wire   [9:0] tmp_s_fu_1142_p4;
wire  signed [30:0] y0i_fu_1177_p1;
wire   [10:0] p_cast7_fu_1198_p1;
wire   [10:0] empty_169_fu_1202_p2;
wire   [8:0] tmp_11_fu_1208_p4;
wire   [11:0] p_cast8_fu_1223_p1;
wire   [11:0] empty_170_fu_1226_p2;
wire   [9:0] tmp_12_fu_1232_p4;
wire   [8:0] shl_ln_fu_1288_p3;
wire   [11:0] zext_ln2146_1_fu_1296_p1;
wire   [11:0] add_ln2146_fu_1300_p2;
wire   [9:0] lshr_ln_fu_1306_p4;
wire   [11:0] add_ln2147_fu_1321_p2;
wire   [9:0] lshr_ln10_fu_1327_p4;
wire   [31:0] xor_ln2148_fu_1342_p2;
wire   [31:0] and_ln2148_fu_1348_p2;
wire   [31:0] xor_ln2149_fu_1360_p2;
wire   [31:0] and_ln2149_fu_1366_p2;
wire   [31:0] xor_ln2150_fu_1378_p2;
wire   [31:0] and_ln2150_fu_1384_p2;
wire   [31:0] xor_ln2151_fu_1396_p2;
wire   [31:0] and_ln2151_fu_1402_p2;
wire   [31:0] or_ln2153_fu_1414_p2;
wire   [31:0] add_ln2153_fu_1420_p2;
wire   [0:0] tmp_15_fu_1426_p3;
wire   [0:0] xor_ln2153_fu_1434_p2;
wire   [31:0] select_ln2153_fu_1440_p3;
wire   [31:0] and_ln2162_fu_1466_p2;
wire   [31:0] xor_ln2163_fu_1478_p2;
wire   [31:0] and_ln2164_fu_1490_p2;
wire   [31:0] a0_2_fu_1484_p2;
wire   [62:0] shl_ln14_fu_1508_p3;
wire   [31:0] a1_2_fu_1472_p2;
wire   [63:0] zext_ln2166_fu_1516_p1;
wire   [63:0] zext_ln2166_1_fu_1520_p1;
wire   [31:0] b0_2_fu_1502_p2;
wire   [62:0] shl_ln15_fu_1530_p3;
wire   [31:0] b1_2_fu_1496_p2;
wire   [63:0] zext_ln2167_fu_1538_p1;
wire   [63:0] zext_ln2167_1_fu_1542_p1;
wire   [63:0] rz_fu_1568_p2;
wire   [63:0] xor_ln2205_fu_1580_p2;
wire   [63:0] xor_ln2204_fu_1574_p2;
wire   [63:0] and_ln2205_fu_1586_p2;
wire   [63:0] xor_ln2204_1_fu_1592_p2;
wire   [31:0] zext_ln2184_fu_1552_p1;
wire   [31:0] lshr_ln2217_fu_1606_p2;
wire   [31:0] lshr_ln2218_fu_1616_p2;
wire   [0:0] trunc_ln2219_fu_1622_p1;
wire   [0:0] rt_fu_1598_p3;
wire   [0:0] and_ln2219_fu_1626_p2;
wire   [0:0] oa_fu_1612_p1;
wire   [0:0] and_ln2220_fu_1638_p2;
wire   [0:0] xor_ln2220_fu_1644_p2;
wire   [0:0] xor_ln2221_fu_1656_p2;
wire   [0:0] cAB_fu_1632_p2;
wire   [31:0] select_ln2226_fu_1668_p3;
wire   [31:0] and_ln2226_fu_1676_p2;
wire   [63:0] select_ln2227_fu_1688_p3;
wire   [63:0] and_ln2227_fu_1696_p2;
wire   [63:0] and_ln2228_fu_1708_p2;
wire   [63:0] and_ln2229_fu_1720_p2;
wire   [0:0] cBA_fu_1650_p2;
wire   [31:0] a_lo_2_fu_1682_p2;
wire   [31:0] select_ln2230_fu_1732_p3;
wire   [31:0] and_ln2230_fu_1740_p2;
wire   [63:0] a_hi_2_fu_1702_p2;
wire   [63:0] select_ln2231_fu_1752_p3;
wire   [63:0] and_ln2231_fu_1760_p2;
wire   [63:0] pa_1_fu_1714_p2;
wire   [63:0] and_ln2232_fu_1772_p2;
wire   [63:0] pb_1_fu_1726_p2;
wire   [63:0] and_ln2233_fu_1784_p2;
wire   [0:0] xor_ln2238_fu_1796_p2;
wire   [0:0] and_ln2238_1_fu_1802_p2;
wire   [31:0] select_ln2238_fu_1808_p3;
wire   [31:0] and_ln2238_fu_1816_p2;
wire   [63:0] select_ln2239_fu_1828_p3;
wire   [63:0] and_ln2239_fu_1836_p2;
wire   [63:0] and_ln2240_fu_1848_p2;
wire   [62:0] lshr_ln12_fu_1860_p4;
wire   [63:0] zext_ln2241_fu_1870_p1;
wire   [0:0] cA_fu_1662_p2;
wire   [63:0] xor_ln2241_fu_1874_p2;
wire   [63:0] select_ln2241_fu_1880_p3;
wire   [63:0] and_ln2241_fu_1888_p2;
wire   [31:0] b_lo_2_fu_1746_p2;
wire   [31:0] select_ln2242_fu_1900_p3;
wire   [31:0] and_ln2242_fu_1908_p2;
wire   [63:0] qa_1_fu_1778_p2;
wire   [63:0] and_ln2243_fu_1920_p2;
wire   [63:0] qb_1_fu_1790_p2;
wire   [63:0] and_ln2244_fu_1932_p2;
wire   [63:0] b_hi_2_fu_1766_p2;
wire   [62:0] lshr_ln13_fu_1944_p4;
wire   [63:0] zext_ln2245_fu_1954_p1;
wire   [63:0] xor_ln2245_fu_1958_p2;
wire   [63:0] and_ln2245_fu_1964_p2;
wire   [8:0] shl_ln17_fu_1988_p3;
wire   [11:0] add_ln1830_fu_2000_p2;
wire   [9:0] lshr_ln14_fu_2006_p4;
wire   [11:0] add_ln1831_fu_2021_p2;
wire   [9:0] lshr_ln15_fu_2027_p4;
wire   [31:0] mul_ln1832_fu_2086_p1;
wire   [63:0] zext_ln1832_fu_2082_p1;
wire   [31:0] mul_ln1832_1_fu_2096_p1;
wire   [63:0] zext_ln1832_1_fu_2092_p1;
wire  signed [63:0] sext_ln1826_fu_2102_p1;
wire   [63:0] mul_ln1832_1_fu_2096_p2;
wire   [63:0] add_ln1832_fu_2106_p2;
wire   [63:0] mul_ln1832_fu_2086_p2;
wire   [31:0] mul_ln1833_fu_2118_p1;
wire   [31:0] mul_ln1833_1_fu_2124_p1;
wire  signed [63:0] sext_ln1826_1_fu_2130_p1;
wire   [63:0] mul_ln1833_1_fu_2124_p2;
wire   [63:0] add_ln1833_fu_2134_p2;
wire   [63:0] mul_ln1833_fu_2118_p2;
wire   [63:0] za_fu_2112_p2;
wire   [30:0] trunc_ln1835_fu_2146_p1;
wire   [11:0] add_ln1835_fu_2155_p2;
wire   [9:0] lshr_ln16_fu_2160_p4;
wire   [63:0] zb_fu_2140_p2;
wire   [30:0] trunc_ln1836_fu_2175_p1;
wire   [11:0] add_ln1836_fu_2184_p2;
wire   [9:0] lshr_ln17_fu_2189_p4;
wire   [8:0] shl_ln18_fu_2236_p3;
wire   [11:0] zext_ln1796_2_fu_2244_p1;
wire   [11:0] add_ln1796_fu_2248_p2;
wire   [9:0] lshr_ln18_fu_2254_p4;
wire   [30:0] trunc_ln1797_fu_2293_p1;
wire   [31:0] xor_ln1797_fu_2297_p2;
wire   [31:0] zext_ln1793_fu_2311_p1;
wire   [30:0] xor_ln1797_2_fu_2306_p2;
wire   [30:0] zext_ln1797_fu_2302_p1;
wire   [30:0] add_ln1794_fu_2321_p2;
wire   [31:0] aw_6_fu_2315_p2;
wire   [8:0] shl_ln1796_1_fu_2352_p3;
wire   [11:0] zext_ln1796_3_fu_2360_p1;
wire   [11:0] add_ln1796_1_fu_2364_p2;
wire   [9:0] lshr_ln1796_1_fu_2370_p4;
wire   [63:0] shl_ln2255_fu_2385_p2;
wire   [63:0] select_ln2255_fu_2391_p3;
wire   [63:0] and_ln2255_fu_2398_p2;
wire   [63:0] shl_ln2256_fu_2411_p2;
wire   [63:0] and_ln2256_fu_2417_p2;
wire   [63:0] shl_ln2257_fu_2430_p2;
wire   [63:0] select_ln2257_fu_2436_p3;
wire   [63:0] and_ln2257_fu_2443_p2;
wire   [63:0] shl_ln2258_fu_2456_p2;
wire   [63:0] and_ln2258_fu_2462_p2;
wire   [30:0] trunc_ln1797_1_fu_2485_p1;
wire   [31:0] xor_ln1797_1_fu_2489_p2;
wire   [31:0] zext_ln1793_1_fu_2503_p1;
wire   [30:0] xor_ln1797_3_fu_2498_p2;
wire   [30:0] zext_ln1797_1_fu_2494_p1;
wire   [30:0] add_ln1794_1_fu_2513_p2;
wire   [31:0] aw_8_fu_2507_p2;
wire   [8:0] shl_ln16_fu_2552_p3;
wire   [11:0] zext_ln2271_1_fu_2560_p1;
wire   [11:0] add_ln2271_fu_2564_p2;
wire   [9:0] lshr_ln11_fu_2570_p4;
wire   [31:0] sub_ln2273_fu_2607_p2;
wire   [31:0] or_ln2273_fu_2613_p2;
wire   [0:0] tmp_16_fu_2619_p3;
wire   [0:0] trunc_ln2273_fu_2633_p1;
wire   [0:0] xor_ln2273_fu_2627_p2;
wire   [0:0] and_ln2273_fu_2641_p2;
wire   [0:0] trunc_ln2273_1_fu_2637_p1;
wire   [0:0] and_ln2273_1_fu_2647_p2;
reg   [0:0] ap_return_preg;
reg   [33:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
reg    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
reg    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 34'd1;
#0 grp_zint_co_reduce_mod_1_fu_674_ap_start_reg = 1'b0;
#0 ap_return_preg = 1'd0;
end

solve_NTRU_zint_co_reduce_mod_1 grp_zint_co_reduce_mod_1_fu_674(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_zint_co_reduce_mod_1_fu_674_ap_start),
    .ap_done(grp_zint_co_reduce_mod_1_fu_674_ap_done),
    .ap_idle(grp_zint_co_reduce_mod_1_fu_674_ap_idle),
    .ap_ready(grp_zint_co_reduce_mod_1_fu_674_ap_ready),
    .vla1_address0(grp_zint_co_reduce_mod_1_fu_674_vla1_address0),
    .vla1_ce0(grp_zint_co_reduce_mod_1_fu_674_vla1_ce0),
    .vla1_we0(grp_zint_co_reduce_mod_1_fu_674_vla1_we0),
    .vla1_d0(grp_zint_co_reduce_mod_1_fu_674_vla1_d0),
    .vla1_q0(vla1_q0),
    .vla1_address1(grp_zint_co_reduce_mod_1_fu_674_vla1_address1),
    .vla1_ce1(grp_zint_co_reduce_mod_1_fu_674_vla1_ce1),
    .vla1_we1(grp_zint_co_reduce_mod_1_fu_674_vla1_we1),
    .vla1_d1(grp_zint_co_reduce_mod_1_fu_674_vla1_d1),
    .vla1_q1(vla1_q1),
    .a(grp_zint_co_reduce_mod_1_fu_674_a),
    .b(grp_zint_co_reduce_mod_1_fu_674_b),
    .m(grp_zint_co_reduce_mod_1_fu_674_m),
    .m0i(grp_zint_co_reduce_mod_1_fu_674_m0i),
    .xa(pa_3_reg_3123),
    .xb(pb_3_reg_3128),
    .ya(qa_3_reg_3133),
    .yb(qb_3_reg_3138)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U174(
    .din0(trunc_ln651_fu_702_p1),
    .din1(y_fu_706_p2),
    .dout(mul_ln656_fu_712_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U175(
    .din0(y_6_fu_724_p0),
    .din1(y_fu_706_p2),
    .dout(y_6_fu_724_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U176(
    .din0(trunc_ln651_fu_702_p1),
    .din1(y_6_fu_724_p2),
    .dout(mul_ln657_fu_730_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U177(
    .din0(y_7_fu_742_p0),
    .din1(y_6_fu_724_p2),
    .dout(y_7_fu_742_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U178(
    .din0(trunc_ln651_1_fu_748_p1),
    .din1(y_10_fu_752_p2),
    .dout(mul_ln656_3_fu_758_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U179(
    .din0(y_11_fu_770_p0),
    .din1(y_10_fu_752_p2),
    .dout(y_11_fu_770_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U180(
    .din0(trunc_ln651_reg_2670),
    .din1(y_7_reg_2676),
    .dout(mul_ln658_fu_776_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U181(
    .din0(trunc_ln651_1_reg_2682),
    .din1(y_11_reg_2689),
    .dout(mul_ln657_3_fu_780_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U182(
    .din0(y_12_fu_790_p0),
    .din1(y_11_reg_2689),
    .dout(y_12_fu_790_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U183(
    .din0(trunc_ln651_1_reg_2682),
    .din1(y_12_fu_790_p2),
    .dout(mul_ln658_2_fu_795_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U184(
    .din0(y_15_fu_885_p0),
    .din1(y_7_reg_2676),
    .dout(y_15_fu_885_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U185(
    .din0(trunc_ln651_reg_2670),
    .din1(y_15_fu_885_p2),
    .dout(mul_ln659_fu_890_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U186(
    .din0(sub_ln658_1_reg_2733),
    .din1(y_12_reg_2700),
    .dout(y_17_fu_975_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U187(
    .din0(trunc_ln651_1_reg_2682),
    .din1(y_17_reg_2771),
    .dout(mul_ln659_1_fu_989_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U188(
    .din0(sub_ln659_reg_2777),
    .din1(x0i_fu_1087_p1),
    .dout(x0i_fu_1087_p2)
);

solve_NTRU_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U189(
    .din0(sub_ln659_1_reg_2782),
    .din1(y0i_fu_1177_p1),
    .dout(y0i_fu_1177_p2)
);

solve_NTRU_mul_64s_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_64s_32ns_64_1_1_U190(
    .din0(pa_reg_549),
    .din1(mul_ln1832_fu_2086_p1),
    .dout(mul_ln1832_fu_2086_p2)
);

solve_NTRU_mul_64s_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_64s_32ns_64_1_1_U191(
    .din0(pb_reg_537),
    .din1(mul_ln1832_1_fu_2096_p1),
    .dout(mul_ln1832_1_fu_2096_p2)
);

solve_NTRU_mul_64s_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_64s_32ns_64_1_1_U192(
    .din0(qa_reg_525),
    .din1(mul_ln1833_fu_2118_p1),
    .dout(mul_ln1833_fu_2118_p2)
);

solve_NTRU_mul_64s_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_64s_32ns_64_1_1_U193(
    .din0(qb_reg_513),
    .din1(mul_ln1833_1_fu_2124_p1),
    .dout(mul_ln1833_1_fu_2124_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state34)) begin
            ap_return_preg <= and_ln2273_1_fu_2647_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_zint_co_reduce_mod_1_fu_674_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state29) | ((icmp_ln1793_1_fu_2340_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26)))) begin
            grp_zint_co_reduce_mod_1_fu_674_ap_start_reg <= 1'b1;
        end else if ((grp_zint_co_reduce_mod_1_fu_674_ap_ready == 1'b1)) begin
            grp_zint_co_reduce_mod_1_fu_674_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2143_fu_1460_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        a0_reg_467 <= a0_1_fu_1354_p2;
    end else if (((icmp_ln2120_fu_1277_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        a0_reg_467 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2143_fu_1460_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        a1_reg_456 <= a1_1_fu_1372_p2;
    end else if (((icmp_ln2120_fu_1277_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        a1_reg_456 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2184_fu_1556_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        a_hi_1_reg_588 <= a_hi_3_fu_1894_p2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        a_hi_1_reg_588 <= a_hi_reg_2952;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2184_fu_1556_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        a_lo_1_reg_570 <= a_lo_3_fu_1822_p2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        a_lo_1_reg_570 <= vla1_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2143_fu_1460_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        b0_reg_445 <= b0_1_fu_1390_p2;
    end else if (((icmp_ln2120_fu_1277_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        b0_reg_445 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2143_fu_1460_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        b1_reg_434 <= b1_1_fu_1408_p2;
    end else if (((icmp_ln2120_fu_1277_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        b1_reg_434 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2184_fu_1556_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        b_hi_1_reg_579 <= b_hi_3_fu_1970_p2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        b_hi_1_reg_579 <= b_hi_reg_2957;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2184_fu_1556_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        b_lo_1_reg_561 <= b_lo_3_fu_1914_p2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        b_lo_1_reg_561 <= vla1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2143_fu_1460_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        c0_2_reg_489 <= c0_fu_1448_p2;
    end else if (((icmp_ln2120_fu_1277_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        c0_2_reg_489 <= 32'd4294967295;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2143_fu_1460_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        c1_reg_478 <= c0_2_reg_489;
    end else if (((icmp_ln2120_fu_1277_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        c1_reg_478 <= 32'd4294967295;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        cc_12_reg_653 <= aw_8_fu_2507_p2[32'd31];
    end else if (((icmp_ln1793_fu_2224_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        cc_12_reg_653 <= ccb_reg_597[32'd32];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        cc_reg_632 <= aw_6_fu_2315_p2[32'd31];
    end else if (((icmp_ln1826_fu_1976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        cc_reg_632 <= cca_reg_609[32'd32];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2184_fu_1556_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        cca_reg_609 <= 33'd0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        cca_reg_609 <= {{za_fu_2112_p2[63:31]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2184_fu_1556_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        ccb_reg_597 <= 33'd0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        ccb_reg_597 <= {{zb_fu_2140_p2[63:31]}};
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond95_fu_1041_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        empty_164_fu_166 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state10) & (exitcond94_fu_1071_p2 == 1'd0))) begin
        empty_164_fu_166 <= empty_165_fu_1065_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond96_fu_965_p2 == 1'd1))) begin
        empty_172_fu_162 <= 7'd0;
    end else if (((exitcond95_fu_1041_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        empty_172_fu_162 <= add_ptr7_sum_fu_1002_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2184_fu_1556_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        i_reg_502 <= i_1_fu_1562_p2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        i_reg_502 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2143_fu_1460_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        j_1_reg_421 <= j_5_fu_1454_p2;
    end else if (((icmp_ln2120_fu_1277_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        j_1_reg_421 <= 7'd105;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2120_fu_1277_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        j_3_fu_182 <= 7'd1;
    end else if (((icmp_ln2270_fu_2546_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state32))) begin
        j_3_fu_182 <= j_7_fu_2585_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2143_fu_1460_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        j_reg_410 <= j_1_reg_421;
    end else if (((icmp_ln2120_fu_1277_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        j_reg_410 <= 7'd106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (exitcond94_fu_1071_p2 == 1'd1))) begin
        loop_index14_fu_170 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) & (exitcond93_fu_1162_p2 == 1'd0))) begin
        loop_index14_fu_170 <= empty_168_fu_1157_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (exitcond97_fu_865_p2 == 1'd1))) begin
        loop_index20_fu_158 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) & (exitcond96_fu_965_p2 == 1'd0))) begin
        loop_index20_fu_158 <= empty_162_fu_960_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        loop_index26_fu_154 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (exitcond97_fu_865_p2 == 1'd0))) begin
        loop_index26_fu_154 <= empty_159_fu_860_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (exitcond93_fu_1162_p2 == 1'd1))) begin
        loop_index_fu_174 <= 7'd0;
    end else if (((exitcond92_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        loop_index_fu_174 <= empty_171_fu_1247_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond92_fu_1252_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        num_fu_178 <= 13'd6602;
    end else if (((icmp_ln1793_1_fu_2340_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26))) begin
        num_fu_178 <= num_3_fu_2475_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2184_fu_1556_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        pa_reg_549 <= pa_2_fu_1842_p2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        pa_reg_549 <= 64'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2184_fu_1556_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        pb_reg_537 <= pb_2_fu_1854_p2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        pb_reg_537 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2184_fu_1556_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        qa_reg_525 <= qa_2_fu_1926_p2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        qa_reg_525 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2184_fu_1556_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        qb_reg_513 <= qb_2_fu_1938_p2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        qb_reg_513 <= 64'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        rc_1_fu_186 <= rc_fu_2532_p2;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        rc_1_fu_186 <= rc_2_fu_2596_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        u_20_reg_642 <= u_33_reg_3077;
    end else if (((icmp_ln1826_fu_1976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        u_20_reg_642 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        u_23_reg_663 <= u_35_reg_3112;
    end else if (((icmp_ln1793_fu_2224_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        u_23_reg_663 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2184_fu_1556_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        u_reg_621 <= 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        u_reg_621 <= u_34_reg_3023;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2143_fu_1460_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        a_hi_reg_2952 <= a_hi_fu_1524_p2;
        b_hi_reg_2957 <= b_hi_fu_1546_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1826_fu_1976_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        icmp_ln1834_reg_3044 <= icmp_ln1834_fu_2042_p2;
        zext_ln1830_1_reg_3028[8 : 2] <= zext_ln1830_1_fu_1996_p1[8 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln658_2_reg_2705 <= mul_ln658_2_fu_795_p2;
        mul_ln658_reg_2695 <= mul_ln658_fu_776_p2;
        y_12_reg_2700 <= y_12_fu_790_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (exitcond97_fu_865_p2 == 1'd1))) begin
        mul_ln659_reg_2743 <= mul_ln659_fu_890_p2;
        sub_ln658_1_reg_2733 <= sub_ln658_1_fu_880_p2;
        y_15_reg_2738 <= y_15_fu_885_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1826_fu_1976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        nega_reg_3048 <= cca_reg_609[32'd32];
        select_ln1784_reg_3054[30 : 0] <= select_ln1784_fu_2066_p3[30 : 0];
        select_ln1797_reg_3059 <= select_ln1797_fu_2074_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1793_fu_2224_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        negb_reg_3088 <= ccb_reg_597[32'd32];
        select_ln1784_1_reg_3094[30 : 0] <= select_ln1784_1_fu_2277_p3[30 : 0];
        select_ln1797_1_reg_3099 <= select_ln1797_1_fu_2285_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1793_1_fu_2340_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26))) begin
        pa_3_reg_3123 <= pa_3_fu_2404_p2;
        pb_3_reg_3128 <= pb_3_fu_2423_p2;
        qa_3_reg_3133 <= qa_3_fu_2449_p2;
        qb_3_reg_3138 <= qb_3_fu_2468_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        sub_ln659_1_reg_2782 <= sub_ln659_1_fu_993_p2;
        sub_ln659_reg_2777 <= sub_ln659_fu_984_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_10_reg_2843[8 : 2] <= tmp_10_fu_1190_p3[8 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_3_reg_2751[8 : 2] <= tmp_3_fu_903_p3[8 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        tmp_8_reg_2815[8 : 2] <= tmp_8_fu_1100_p3[8 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_reg_2713[8 : 2] <= tmp_fu_803_p3[8 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln651_1_reg_2682 <= trunc_ln651_1_fu_748_p1;
        trunc_ln651_reg_2670 <= trunc_ln651_fu_702_p1;
        y_11_reg_2689 <= y_11_fu_770_p2;
        y_7_reg_2676 <= y_7_fu_742_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        u_33_reg_3077 <= u_33_fu_2230_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        u_34_reg_3023 <= u_34_fu_1982_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        u_35_reg_3112 <= u_35_fu_2346_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1793_fu_2224_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        vla1_addr_52_reg_3082[9 : 0] <= zext_ln1796_fu_2264_p1[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1793_1_fu_2340_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state26))) begin
        vla1_addr_53_reg_3117[9 : 0] <= zext_ln1796_1_fu_2380_p1[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (exitcond94_fu_1071_p2 == 1'd1))) begin
        x0i_reg_2807 <= x0i_fu_1087_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (exitcond93_fu_1162_p2 == 1'd1))) begin
        y0i_reg_2835 <= y0i_fu_1177_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond96_fu_965_p2 == 1'd1))) begin
        y_17_reg_2771 <= y_17_fu_975_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

always @ (*) begin
    if ((grp_zint_co_reduce_mod_1_fu_674_ap_done == 1'b0)) begin
        ap_ST_fsm_state28_blk = 1'b1;
    end else begin
        ap_ST_fsm_state28_blk = 1'b0;
    end
end

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_zint_co_reduce_mod_1_fu_674_ap_done == 1'b0)) begin
        ap_ST_fsm_state30_blk = 1'b1;
    end else begin
        ap_ST_fsm_state30_blk = 1'b0;
    end
end

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        ap_return = and_ln2273_1_fu_2647_p2;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_zint_co_reduce_mod_1_fu_674_a = 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        grp_zint_co_reduce_mod_1_fu_674_a = 8'd168;
    end else begin
        grp_zint_co_reduce_mod_1_fu_674_a = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_zint_co_reduce_mod_1_fu_674_b = 12'd2120;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        grp_zint_co_reduce_mod_1_fu_674_b = 12'd1696;
    end else begin
        grp_zint_co_reduce_mod_1_fu_674_b = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_zint_co_reduce_mod_1_fu_674_m = 11'd848;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        grp_zint_co_reduce_mod_1_fu_674_m = 11'd1272;
    end else begin
        grp_zint_co_reduce_mod_1_fu_674_m = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_zint_co_reduce_mod_1_fu_674_m0i = x0i_reg_2807;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        grp_zint_co_reduce_mod_1_fu_674_m0i = y0i_reg_2835;
    end else begin
        grp_zint_co_reduce_mod_1_fu_674_m0i = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln2270_fu_2546_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state32))) begin
        vla1_address0 = vla1_addr_28_reg_2665;
    end else if (((icmp_ln2270_fu_2546_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state32))) begin
        vla1_address0 = zext_ln2271_fu_2580_p1;
    end else if (((icmp_ln1793_1_fu_2340_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state26))) begin
        vla1_address0 = zext_ln1796_1_fu_2380_p1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        vla1_address0 = zext_ln1796_fu_2264_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        vla1_address0 = zext_ln1836_fu_2199_p1;
    end else if (((icmp_ln1826_fu_1976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        vla1_address0 = 64'd847;
    end else if (((icmp_ln1826_fu_1976_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        vla1_address0 = zext_ln1831_fu_2037_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        vla1_address0 = 64'd742;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        vla1_address0 = zext_ln2147_fu_1337_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        vla1_address0 = 64'd530;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        vla1_address0 = p_cast18_fu_1242_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        vla1_address0 = p_cast16_fu_1152_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        vla1_address0 = p_cast14_fu_1060_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        vla1_address0 = 64'd106;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        vla1_address0 = p_cast11_fu_931_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        vla1_address0 = p_cast9_fu_831_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        vla1_address0 = 64'd318;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state28))) begin
        vla1_address0 = grp_zint_co_reduce_mod_1_fu_674_vla1_address0;
    end else begin
        vla1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        vla1_address1 = vla1_addr_reg_2660;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        vla1_address1 = vla1_addr_53_reg_3117;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        vla1_address1 = vla1_addr_52_reg_3082;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        vla1_address1 = zext_ln1835_fu_2170_p1;
    end else if (((icmp_ln1826_fu_1976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        vla1_address1 = 64'd741;
    end else if (((icmp_ln1826_fu_1976_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        vla1_address1 = zext_ln1830_fu_2016_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        vla1_address1 = zext_ln2146_fu_1316_p1;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state19))) begin
        vla1_address1 = 64'd636;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        vla1_address1 = 64'd530;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        vla1_address1 = p_cast17_fu_1218_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        vla1_address1 = p_cast15_fu_1128_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        vla1_address1 = p_cast13_fu_1036_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        vla1_address1 = p_cast12_fu_955_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        vla1_address1 = p_cast10_fu_855_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        vla1_address1 = 64'd212;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state28))) begin
        vla1_address1 = grp_zint_co_reduce_mod_1_fu_674_vla1_address1;
    end else begin
        vla1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln2270_fu_2546_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state32)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln2270_fu_2546_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state32)) | ((icmp_ln1793_1_fu_2340_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state26)) | ((icmp_ln1826_fu_1976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((icmp_ln1826_fu_1976_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)))) begin
        vla1_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state28))) begin
        vla1_ce0 = grp_zint_co_reduce_mod_1_fu_674_vla1_ce0;
    end else begin
        vla1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln1826_fu_1976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((icmp_ln1826_fu_1976_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22)))) begin
        vla1_ce1 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state28))) begin
        vla1_ce1 = grp_zint_co_reduce_mod_1_fu_674_vla1_ce1;
    end else begin
        vla1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        vla1_d0 = zext_ln1836_1_fu_2179_p1;
    end else if (((icmp_ln1826_fu_1976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        vla1_d0 = trunc_ln1842_fu_2053_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        vla1_d0 = add_ln2114_fu_1267_p2;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12))) begin
        vla1_d0 = vla1_q1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        vla1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        vla1_d0 = 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state28))) begin
        vla1_d0 = grp_zint_co_reduce_mod_1_fu_674_vla1_d0;
    end else begin
        vla1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        vla1_d1 = zext_ln1798_1_fu_2519_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        vla1_d1 = zext_ln1798_fu_2327_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        vla1_d1 = zext_ln1835_1_fu_2150_p1;
    end else if (((icmp_ln1826_fu_1976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        vla1_d1 = trunc_ln1841_fu_2048_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        vla1_d1 = 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5))) begin
        vla1_d1 = vla1_q0;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state28))) begin
        vla1_d1 = grp_zint_co_reduce_mod_1_fu_674_vla1_d1;
    end else begin
        vla1_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | ((icmp_ln1834_reg_3044 == 1'd0) & (1'b1 == ap_CS_fsm_state23)) | ((icmp_ln1826_fu_1976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)))) begin
        vla1_we0 = 4'd15;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state28))) begin
        vla1_we0 = grp_zint_co_reduce_mod_1_fu_674_vla1_we0;
    end else begin
        vla1_we0 = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | ((icmp_ln1834_reg_3044 == 1'd0) & (1'b1 == ap_CS_fsm_state23)) | ((icmp_ln1826_fu_1976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)))) begin
        vla1_we1 = 4'd15;
    end else if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state28))) begin
        vla1_we1 = grp_zint_co_reduce_mod_1_fu_674_vla1_we1;
    end else begin
        vla1_we1 = 4'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (exitcond97_fu_865_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (exitcond96_fu_965_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((exitcond95_fu_1041_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (exitcond94_fu_1071_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (exitcond93_fu_1162_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((exitcond92_fu_1252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((icmp_ln2120_fu_1277_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln2143_fu_1460_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((icmp_ln2184_fu_1556_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((icmp_ln1826_fu_1976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state24 : begin
            if (((icmp_ln1793_fu_2224_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state26 : begin
            if (((icmp_ln1793_1_fu_2340_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state28 : begin
            if (((grp_zint_co_reduce_mod_1_fu_674_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            if (((grp_zint_co_reduce_mod_1_fu_674_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            if (((icmp_ln2270_fu_2546_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a0_1_fu_1354_p2 = (and_ln2148_fu_1348_p2 ^ a0_reg_467);

assign a0_2_fu_1484_p2 = (xor_ln2163_fu_1478_p2 & a0_reg_467);

assign a1_1_fu_1372_p2 = (and_ln2149_fu_1366_p2 ^ a1_reg_456);

assign a1_2_fu_1472_p2 = (and_ln2162_fu_1466_p2 | a1_1_fu_1372_p2);

assign a_hi_2_fu_1702_p2 = (a_hi_1_reg_588 - and_ln2227_fu_1696_p2);

assign a_hi_3_fu_1894_p2 = (and_ln2241_fu_1888_p2 ^ a_hi_2_fu_1702_p2);

assign a_hi_fu_1524_p2 = (zext_ln2166_fu_1516_p1 + zext_ln2166_1_fu_1520_p1);

assign a_lo_2_fu_1682_p2 = (a_lo_1_reg_570 - and_ln2226_fu_1676_p2);

assign a_lo_3_fu_1822_p2 = (and_ln2238_fu_1816_p2 + a_lo_2_fu_1682_p2);

assign add_ln1794_1_fu_2513_p2 = (xor_ln1797_3_fu_2498_p2 + zext_ln1797_1_fu_2494_p1);

assign add_ln1794_fu_2321_p2 = (xor_ln1797_2_fu_2306_p2 + zext_ln1797_fu_2302_p1);

assign add_ln1796_1_fu_2364_p2 = ($signed(zext_ln1796_3_fu_2360_p1) + $signed(12'd2968));

assign add_ln1796_fu_2248_p2 = ($signed(zext_ln1796_2_fu_2244_p1) + $signed(12'd2544));

assign add_ln1830_fu_2000_p2 = ($signed(zext_ln1830_1_fu_1996_p1) + $signed(12'd2544));

assign add_ln1831_fu_2021_p2 = ($signed(zext_ln1830_1_fu_1996_p1) + $signed(12'd2968));

assign add_ln1832_fu_2106_p2 = ($signed(sext_ln1826_fu_2102_p1) + $signed(mul_ln1832_1_fu_2096_p2));

assign add_ln1833_fu_2134_p2 = ($signed(sext_ln1826_1_fu_2130_p1) + $signed(mul_ln1833_1_fu_2124_p2));

assign add_ln1835_fu_2155_p2 = ($signed(zext_ln1830_1_reg_3028) + $signed(12'd2540));

assign add_ln1836_fu_2184_p2 = ($signed(zext_ln1830_1_reg_3028) + $signed(12'd2964));

assign add_ln2114_fu_1267_p2 = ($signed(vla1_q1) + $signed(32'd4294967295));

assign add_ln2146_fu_1300_p2 = ($signed(zext_ln2146_1_fu_1296_p1) + $signed(12'd2540));

assign add_ln2147_fu_1321_p2 = ($signed(zext_ln2146_1_fu_1296_p1) + $signed(12'd2964));

assign add_ln2153_fu_1420_p2 = (or_ln2153_fu_1414_p2 + 32'd2147483647);

assign add_ln2271_fu_2564_p2 = ($signed(zext_ln2271_1_fu_2560_p1) + $signed(12'd2544));

assign add_ptr7_sum_fu_1002_p2 = (empty_172_fu_162 + 7'd1);

assign and_ln2148_fu_1348_p2 = (xor_ln2148_fu_1342_p2 & c0_2_reg_489);

assign and_ln2149_fu_1366_p2 = (xor_ln2149_fu_1360_p2 & c1_reg_478);

assign and_ln2150_fu_1384_p2 = (xor_ln2150_fu_1378_p2 & c0_2_reg_489);

assign and_ln2151_fu_1402_p2 = (xor_ln2151_fu_1396_p2 & c1_reg_478);

assign and_ln2162_fu_1466_p2 = (c0_2_reg_489 & a0_1_fu_1354_p2);

assign and_ln2164_fu_1490_p2 = (c0_2_reg_489 & b0_1_fu_1390_p2);

assign and_ln2205_fu_1586_p2 = (xor_ln2205_fu_1580_p2 & xor_ln2204_fu_1574_p2);

assign and_ln2219_fu_1626_p2 = (trunc_ln2219_fu_1622_p1 & rt_fu_1598_p3);

assign and_ln2220_fu_1638_p2 = (trunc_ln2219_fu_1622_p1 & oa_fu_1612_p1);

assign and_ln2226_fu_1676_p2 = (select_ln2226_fu_1668_p3 & b_lo_1_reg_561);

assign and_ln2227_fu_1696_p2 = (select_ln2227_fu_1688_p3 & b_hi_1_reg_579);

assign and_ln2228_fu_1708_p2 = (select_ln2227_fu_1688_p3 & qa_reg_525);

assign and_ln2229_fu_1720_p2 = (select_ln2227_fu_1688_p3 & qb_reg_513);

assign and_ln2230_fu_1740_p2 = (select_ln2230_fu_1732_p3 & a_lo_2_fu_1682_p2);

assign and_ln2231_fu_1760_p2 = (select_ln2231_fu_1752_p3 & a_hi_2_fu_1702_p2);

assign and_ln2232_fu_1772_p2 = (select_ln2231_fu_1752_p3 & pa_1_fu_1714_p2);

assign and_ln2233_fu_1784_p2 = (select_ln2231_fu_1752_p3 & pb_1_fu_1726_p2);

assign and_ln2238_1_fu_1802_p2 = (xor_ln2238_fu_1796_p2 & oa_fu_1612_p1);

assign and_ln2238_fu_1816_p2 = (select_ln2238_fu_1808_p3 & a_lo_2_fu_1682_p2);

assign and_ln2239_fu_1836_p2 = (select_ln2239_fu_1828_p3 & pa_1_fu_1714_p2);

assign and_ln2240_fu_1848_p2 = (select_ln2239_fu_1828_p3 & pb_1_fu_1726_p2);

assign and_ln2241_fu_1888_p2 = (xor_ln2241_fu_1874_p2 & select_ln2241_fu_1880_p3);

assign and_ln2242_fu_1908_p2 = (select_ln2242_fu_1900_p3 & b_lo_2_fu_1746_p2);

assign and_ln2243_fu_1920_p2 = (select_ln2241_fu_1880_p3 & qa_1_fu_1778_p2);

assign and_ln2244_fu_1932_p2 = (select_ln2241_fu_1880_p3 & qb_1_fu_1790_p2);

assign and_ln2245_fu_1964_p2 = (xor_ln2245_fu_1958_p2 & select_ln2239_fu_1828_p3);

assign and_ln2255_fu_2398_p2 = (shl_ln2255_fu_2385_p2 & select_ln2255_fu_2391_p3);

assign and_ln2256_fu_2417_p2 = (shl_ln2256_fu_2411_p2 & select_ln2255_fu_2391_p3);

assign and_ln2257_fu_2443_p2 = (shl_ln2257_fu_2430_p2 & select_ln2257_fu_2436_p3);

assign and_ln2258_fu_2462_p2 = (shl_ln2258_fu_2456_p2 & select_ln2257_fu_2436_p3);

assign and_ln2273_1_fu_2647_p2 = (trunc_ln2273_1_fu_2637_p1 & and_ln2273_fu_2641_p2);

assign and_ln2273_fu_2641_p2 = (xor_ln2273_fu_2627_p2 & trunc_ln2273_fu_2633_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign aw_6_fu_2315_p2 = (xor_ln1797_fu_2297_p2 + zext_ln1793_fu_2311_p1);

assign aw_8_fu_2507_p2 = (xor_ln1797_1_fu_2489_p2 + zext_ln1793_1_fu_2503_p1);

assign b0_1_fu_1390_p2 = (b0_reg_445 ^ and_ln2150_fu_1384_p2);

assign b0_2_fu_1502_p2 = (xor_ln2163_fu_1478_p2 & b0_reg_445);

assign b1_1_fu_1408_p2 = (b1_reg_434 ^ and_ln2151_fu_1402_p2);

assign b1_2_fu_1496_p2 = (b1_1_fu_1408_p2 | and_ln2164_fu_1490_p2);

assign b_hi_2_fu_1766_p2 = (b_hi_1_reg_579 - and_ln2231_fu_1760_p2);

assign b_hi_3_fu_1970_p2 = (b_hi_2_fu_1766_p2 ^ and_ln2245_fu_1964_p2);

assign b_hi_fu_1546_p2 = (zext_ln2167_fu_1538_p1 + zext_ln2167_1_fu_1542_p1);

assign b_lo_2_fu_1746_p2 = (b_lo_1_reg_561 - and_ln2230_fu_1740_p2);

assign b_lo_3_fu_1914_p2 = (and_ln2242_fu_1908_p2 + b_lo_2_fu_1746_p2);

assign c0_fu_1448_p2 = (select_ln2153_fu_1440_p3 & c0_2_reg_489);

assign cAB_fu_1632_p2 = (oa_fu_1612_p1 & and_ln2219_fu_1626_p2);

assign cA_fu_1662_p2 = (xor_ln2221_fu_1656_p2 | and_ln2219_fu_1626_p2);

assign cBA_fu_1650_p2 = (xor_ln2220_fu_1644_p2 & and_ln2220_fu_1638_p2);

assign empty_158_fu_839_p2 = ($signed(p_cast1_fu_836_p1) + $signed(12'd2544));

assign empty_159_fu_860_p2 = (loop_index26_fu_154 + 7'd1);

assign empty_160_fu_915_p2 = ($signed(p_cast2_fu_911_p1) + $signed(11'd1272));

assign empty_161_fu_939_p2 = ($signed(p_cast3_fu_936_p1) + $signed(12'd2968));

assign empty_162_fu_960_p2 = (loop_index20_fu_158 + 7'd1);

assign empty_163_fu_1020_p2 = (p_cast4_fu_1016_p1 + 10'd424);

assign empty_165_fu_1065_p2 = (empty_164_fu_166 + 7'd1);

assign empty_166_fu_1112_p2 = ($signed(p_cast5_fu_1108_p1) + $signed(11'd1272));

assign empty_167_fu_1136_p2 = (p_cast6_fu_1133_p1 + 12'd1696);

assign empty_168_fu_1157_p2 = (loop_index14_fu_170 + 7'd1);

assign empty_169_fu_1202_p2 = (p_cast7_fu_1198_p1 + 11'd848);

assign empty_170_fu_1226_p2 = ($signed(p_cast8_fu_1223_p1) + $signed(12'd2120));

assign empty_171_fu_1247_p2 = (loop_index_fu_174 + 7'd1);

assign empty_fu_815_p2 = (p_cast_fu_811_p1 + 11'd848);

assign exitcond92_fu_1252_p2 = ((loop_index_fu_174 == 7'd105) ? 1'b1 : 1'b0);

assign exitcond93_fu_1162_p2 = ((loop_index14_fu_170 == 7'd105) ? 1'b1 : 1'b0);

assign exitcond94_fu_1071_p2 = ((empty_164_fu_166 == 7'd105) ? 1'b1 : 1'b0);

assign exitcond95_fu_1041_p2 = ((empty_172_fu_162 == 7'd104) ? 1'b1 : 1'b0);

assign exitcond96_fu_965_p2 = ((loop_index20_fu_158 == 7'd105) ? 1'b1 : 1'b0);

assign exitcond97_fu_865_p2 = ((loop_index26_fu_154 == 7'd105) ? 1'b1 : 1'b0);

assign grp_zint_co_reduce_mod_1_fu_674_ap_start = grp_zint_co_reduce_mod_1_fu_674_ap_start_reg;

assign i_1_fu_1562_p2 = (i_reg_502 + 5'd1);

assign icmp_ln1793_1_fu_2340_p2 = ((u_23_reg_663 == 7'd106) ? 1'b1 : 1'b0);

assign icmp_ln1793_fu_2224_p2 = ((u_20_reg_642 == 7'd106) ? 1'b1 : 1'b0);

assign icmp_ln1826_fu_1976_p2 = ((u_reg_621 == 7'd106) ? 1'b1 : 1'b0);

assign icmp_ln1834_fu_2042_p2 = ((u_reg_621 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln2120_fu_1277_p2 = ((num_fu_178 > 13'd29) ? 1'b1 : 1'b0);

assign icmp_ln2143_fu_1460_p2 = ((j_1_reg_421 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln2184_fu_1556_p2 = ((i_reg_502 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln2270_fu_2546_p2 = ((j_3_fu_182 == 7'd106) ? 1'b1 : 1'b0);

assign j_5_fu_1454_p2 = ($signed(j_1_reg_421) + $signed(7'd127));

assign j_7_fu_2585_p2 = (j_3_fu_182 + 7'd1);

assign lshr_ln10_fu_1327_p4 = {{add_ln2147_fu_1321_p2[11:2]}};

assign lshr_ln11_fu_2570_p4 = {{add_ln2271_fu_2564_p2[11:2]}};

assign lshr_ln12_fu_1860_p4 = {{a_hi_2_fu_1702_p2[63:1]}};

assign lshr_ln13_fu_1944_p4 = {{b_hi_2_fu_1766_p2[63:1]}};

assign lshr_ln14_fu_2006_p4 = {{add_ln1830_fu_2000_p2[11:2]}};

assign lshr_ln15_fu_2027_p4 = {{add_ln1831_fu_2021_p2[11:2]}};

assign lshr_ln16_fu_2160_p4 = {{add_ln1835_fu_2155_p2[11:2]}};

assign lshr_ln1796_1_fu_2370_p4 = {{add_ln1796_1_fu_2364_p2[11:2]}};

assign lshr_ln17_fu_2189_p4 = {{add_ln1836_fu_2184_p2[11:2]}};

assign lshr_ln18_fu_2254_p4 = {{add_ln1796_fu_2248_p2[11:2]}};

assign lshr_ln2217_fu_1606_p2 = a_lo_1_reg_570 >> zext_ln2184_fu_1552_p1;

assign lshr_ln2218_fu_1616_p2 = b_lo_1_reg_561 >> zext_ln2184_fu_1552_p1;

assign lshr_ln_fu_1306_p4 = {{add_ln2146_fu_1300_p2[11:2]}};

assign mul_ln1832_1_fu_2096_p1 = zext_ln1832_1_fu_2092_p1;

assign mul_ln1832_fu_2086_p1 = zext_ln1832_fu_2082_p1;

assign mul_ln1833_1_fu_2124_p1 = zext_ln1832_1_fu_2092_p1;

assign mul_ln1833_fu_2118_p1 = zext_ln1832_fu_2082_p1;

assign nega_fu_2058_p3 = cca_reg_609[32'd32];

assign negb_fu_2269_p3 = ccb_reg_597[32'd32];

assign num_3_fu_2475_p2 = ($signed(num_fu_178) + $signed(13'd8162));

assign oa_fu_1612_p1 = lshr_ln2217_fu_1606_p2[0:0];

assign or_ln2153_fu_1414_p2 = (vla1_q1 | vla1_q0);

assign or_ln2273_fu_2613_p2 = (sub_ln2273_fu_2607_p2 | rc_1_fu_186);

assign p_cast10_fu_855_p1 = tmp_2_fu_845_p4;

assign p_cast11_fu_931_p1 = tmp_4_fu_921_p4;

assign p_cast12_fu_955_p1 = tmp_5_fu_945_p4;

assign p_cast13_fu_1036_p1 = tmp_7_fu_1026_p4;

assign p_cast14_fu_1060_p1 = empty_164_fu_166;

assign p_cast15_fu_1128_p1 = tmp_9_fu_1118_p4;

assign p_cast16_fu_1152_p1 = tmp_s_fu_1142_p4;

assign p_cast17_fu_1218_p1 = tmp_11_fu_1208_p4;

assign p_cast18_fu_1242_p1 = tmp_12_fu_1232_p4;

assign p_cast1_fu_836_p1 = tmp_reg_2713;

assign p_cast2_fu_911_p1 = tmp_3_fu_903_p3;

assign p_cast3_fu_936_p1 = tmp_3_reg_2751;

assign p_cast4_fu_1016_p1 = tmp_6_fu_1008_p3;

assign p_cast5_fu_1108_p1 = tmp_8_fu_1100_p3;

assign p_cast6_fu_1133_p1 = tmp_8_reg_2815;

assign p_cast7_fu_1198_p1 = tmp_10_fu_1190_p3;

assign p_cast8_fu_1223_p1 = tmp_10_reg_2843;

assign p_cast9_fu_831_p1 = tmp_1_fu_821_p4;

assign p_cast_fu_811_p1 = tmp_fu_803_p3;

assign pa_1_fu_1714_p2 = ($signed(pa_reg_549) - $signed(and_ln2228_fu_1708_p2));

assign pa_2_fu_1842_p2 = (and_ln2239_fu_1836_p2 + pa_1_fu_1714_p2);

assign pa_3_fu_2404_p2 = ($signed(pa_reg_549) - $signed(and_ln2255_fu_2398_p2));

assign pb_1_fu_1726_p2 = ($signed(pb_reg_537) - $signed(and_ln2229_fu_1720_p2));

assign pb_2_fu_1854_p2 = (and_ln2240_fu_1848_p2 + pb_1_fu_1726_p2);

assign pb_3_fu_2423_p2 = ($signed(pb_reg_537) - $signed(and_ln2256_fu_2417_p2));

assign qa_1_fu_1778_p2 = ($signed(qa_reg_525) - $signed(and_ln2232_fu_1772_p2));

assign qa_2_fu_1926_p2 = (and_ln2243_fu_1920_p2 + qa_1_fu_1778_p2);

assign qa_3_fu_2449_p2 = ($signed(qa_reg_525) - $signed(and_ln2257_fu_2443_p2));

assign qb_1_fu_1790_p2 = ($signed(qb_reg_513) - $signed(and_ln2233_fu_1784_p2));

assign qb_2_fu_1938_p2 = (and_ln2244_fu_1932_p2 + qb_1_fu_1790_p2);

assign qb_3_fu_2468_p2 = ($signed(qb_reg_513) - $signed(and_ln2258_fu_2462_p2));

assign rc_2_fu_2596_p2 = (vla1_q0 | rc_1_fu_186);

assign rc_fu_2532_p2 = (vla1_q1 ^ 32'd1);

assign rt_fu_1598_p3 = xor_ln2204_1_fu_1592_p2[32'd63];

assign rz_fu_1568_p2 = (b_hi_1_reg_579 - a_hi_1_reg_588);

assign select_ln1784_1_fu_2277_p3 = ((negb_fu_2269_p3[0:0] == 1'b1) ? 32'd2147483647 : 32'd0);

assign select_ln1784_fu_2066_p3 = ((nega_fu_2058_p3[0:0] == 1'b1) ? 32'd2147483647 : 32'd0);

assign select_ln1797_1_fu_2285_p3 = ((negb_fu_2269_p3[0:0] == 1'b1) ? 31'd2147483647 : 31'd0);

assign select_ln1797_fu_2074_p3 = ((nega_fu_2058_p3[0:0] == 1'b1) ? 31'd2147483647 : 31'd0);

assign select_ln2153_fu_1440_p3 = ((xor_ln2153_fu_1434_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd0);

assign select_ln2226_fu_1668_p3 = ((cAB_fu_1632_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd0);

assign select_ln2227_fu_1688_p3 = ((cAB_fu_1632_p2[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln2230_fu_1732_p3 = ((cBA_fu_1650_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd0);

assign select_ln2231_fu_1752_p3 = ((cBA_fu_1650_p2[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln2238_fu_1808_p3 = ((and_ln2238_1_fu_1802_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd0);

assign select_ln2239_fu_1828_p3 = ((and_ln2238_1_fu_1802_p2[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln2241_fu_1880_p3 = ((cA_fu_1662_p2[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln2242_fu_1900_p3 = ((cA_fu_1662_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd0);

assign select_ln2255_fu_2391_p3 = ((nega_reg_3048[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln2257_fu_2436_p3 = ((negb_reg_3088[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign sext_ln1826_1_fu_2130_p1 = ccb_reg_597;

assign sext_ln1826_fu_2102_p1 = cca_reg_609;

assign shl_ln14_fu_1508_p3 = {{a0_2_fu_1484_p2}, {31'd0}};

assign shl_ln15_fu_1530_p3 = {{b0_2_fu_1502_p2}, {31'd0}};

assign shl_ln16_fu_2552_p3 = {{j_3_fu_182}, {2'd0}};

assign shl_ln1796_1_fu_2352_p3 = {{u_23_reg_663}, {2'd0}};

assign shl_ln17_fu_1988_p3 = {{u_reg_621}, {2'd0}};

assign shl_ln18_fu_2236_p3 = {{u_20_reg_642}, {2'd0}};

assign shl_ln2255_fu_2385_p2 = pa_reg_549 << 64'd1;

assign shl_ln2256_fu_2411_p2 = pb_reg_537 << 64'd1;

assign shl_ln2257_fu_2430_p2 = qa_reg_525 << 64'd1;

assign shl_ln2258_fu_2456_p2 = qb_reg_513 << 64'd1;

assign shl_ln_fu_1288_p3 = {{j_reg_410}, {2'd0}};

assign sub_ln2273_fu_2607_p2 = (32'd0 - rc_1_fu_186);

assign sub_ln658_1_fu_880_p2 = (31'd2 - mul_ln658_2_reg_2705);

assign sub_ln659_1_fu_993_p2 = (31'd2 - mul_ln659_1_fu_989_p2);

assign sub_ln659_fu_984_p2 = (31'd2 - mul_ln659_reg_2743);

assign tmp_10_fu_1190_p3 = {{loop_index_fu_174}, {2'd0}};

assign tmp_11_fu_1208_p4 = {{empty_169_fu_1202_p2[10:2]}};

assign tmp_12_fu_1232_p4 = {{empty_170_fu_1226_p2[11:2]}};

assign tmp_15_fu_1426_p3 = add_ln2153_fu_1420_p2[32'd31];

assign tmp_16_fu_2619_p3 = or_ln2273_fu_2613_p2[32'd31];

assign tmp_1_fu_821_p4 = {{empty_fu_815_p2[10:2]}};

assign tmp_2_fu_845_p4 = {{empty_158_fu_839_p2[11:2]}};

assign tmp_3_fu_903_p3 = {{loop_index20_fu_158}, {2'd0}};

assign tmp_4_fu_921_p4 = {{empty_160_fu_915_p2[10:2]}};

assign tmp_5_fu_945_p4 = {{empty_161_fu_939_p2[11:2]}};

assign tmp_6_fu_1008_p3 = {{add_ptr7_sum_fu_1002_p2}, {2'd0}};

assign tmp_7_fu_1026_p4 = {{empty_163_fu_1020_p2[9:2]}};

assign tmp_8_fu_1100_p3 = {{loop_index14_fu_170}, {2'd0}};

assign tmp_9_fu_1118_p4 = {{empty_166_fu_1112_p2[10:2]}};

assign tmp_fu_803_p3 = {{loop_index26_fu_154}, {2'd0}};

assign tmp_s_fu_1142_p4 = {{empty_167_fu_1136_p2[11:2]}};

assign trunc_ln1797_1_fu_2485_p1 = vla1_q0[30:0];

assign trunc_ln1797_fu_2293_p1 = vla1_q0[30:0];

assign trunc_ln1835_fu_2146_p1 = za_fu_2112_p2[30:0];

assign trunc_ln1836_fu_2175_p1 = zb_fu_2140_p2[30:0];

assign trunc_ln1841_fu_2048_p1 = cca_reg_609[31:0];

assign trunc_ln1842_fu_2053_p1 = ccb_reg_597[31:0];

assign trunc_ln2219_fu_1622_p1 = lshr_ln2218_fu_1616_p2[0:0];

assign trunc_ln2273_1_fu_2637_p1 = vla1_q0[0:0];

assign trunc_ln2273_fu_2633_p1 = vla1_q1[0:0];

assign trunc_ln651_1_fu_748_p1 = vla1_q0[30:0];

assign trunc_ln651_fu_702_p1 = vla1_q1[30:0];

assign u_33_fu_2230_p2 = (u_20_reg_642 + 7'd1);

assign u_34_fu_1982_p2 = (u_reg_621 + 7'd1);

assign u_35_fu_2346_p2 = (u_23_reg_663 + 7'd1);

assign vla1_addr_28_reg_2665 = 64'd318;

assign vla1_addr_reg_2660 = 64'd212;

assign x0i_fu_1087_p1 = ($signed(31'd0) - $signed(y_15_reg_2738));

assign xor_ln1797_1_fu_2489_p2 = (vla1_q0 ^ select_ln1784_1_reg_3094);

assign xor_ln1797_2_fu_2306_p2 = (trunc_ln1797_fu_2293_p1 ^ select_ln1797_reg_3059);

assign xor_ln1797_3_fu_2498_p2 = (trunc_ln1797_1_fu_2485_p1 ^ select_ln1797_1_reg_3099);

assign xor_ln1797_fu_2297_p2 = (vla1_q0 ^ select_ln1784_reg_3054);

assign xor_ln2148_fu_1342_p2 = (vla1_q1 ^ a0_reg_467);

assign xor_ln2149_fu_1360_p2 = (vla1_q1 ^ a1_reg_456);

assign xor_ln2150_fu_1378_p2 = (vla1_q0 ^ b0_reg_445);

assign xor_ln2151_fu_1396_p2 = (vla1_q0 ^ b1_reg_434);

assign xor_ln2153_fu_1434_p2 = (tmp_15_fu_1426_p3 ^ 1'd1);

assign xor_ln2163_fu_1478_p2 = (c0_2_reg_489 ^ 32'd4294967295);

assign xor_ln2204_1_fu_1592_p2 = (rz_fu_1568_p2 ^ and_ln2205_fu_1586_p2);

assign xor_ln2204_fu_1574_p2 = (b_hi_1_reg_579 ^ a_hi_1_reg_588);

assign xor_ln2205_fu_1580_p2 = (rz_fu_1568_p2 ^ a_hi_1_reg_588);

assign xor_ln2220_fu_1644_p2 = (rt_fu_1598_p3 ^ 1'd1);

assign xor_ln2221_fu_1656_p2 = (oa_fu_1612_p1 ^ 1'd1);

assign xor_ln2238_fu_1796_p2 = (1'd1 ^ and_ln2219_fu_1626_p2);

assign xor_ln2241_fu_1874_p2 = (zext_ln2241_fu_1870_p1 ^ a_hi_2_fu_1702_p2);

assign xor_ln2245_fu_1958_p2 = (zext_ln2245_fu_1954_p1 ^ b_hi_2_fu_1766_p2);

assign xor_ln2273_fu_2627_p2 = (tmp_16_fu_2619_p3 ^ 1'd1);

assign y0i_fu_1177_p1 = ($signed(31'd0) - $signed(y_17_reg_2771));

assign y_10_fu_752_p2 = ($signed(31'd2) - $signed(trunc_ln651_1_fu_748_p1));

assign y_11_fu_770_p0 = (31'd2 - mul_ln656_3_fu_758_p2);

assign y_12_fu_790_p0 = (31'd2 - mul_ln657_3_fu_780_p2);

assign y_15_fu_885_p0 = (31'd2 - mul_ln658_reg_2695);

assign y_6_fu_724_p0 = (31'd2 - mul_ln656_fu_712_p2);

assign y_7_fu_742_p0 = (31'd2 - mul_ln657_fu_730_p2);

assign y_fu_706_p2 = ($signed(31'd2) - $signed(trunc_ln651_fu_702_p1));

assign za_fu_2112_p2 = (add_ln1832_fu_2106_p2 + mul_ln1832_fu_2086_p2);

assign zb_fu_2140_p2 = (add_ln1833_fu_2134_p2 + mul_ln1833_fu_2118_p2);

assign zext_ln1793_1_fu_2503_p1 = cc_12_reg_653;

assign zext_ln1793_fu_2311_p1 = cc_reg_632;

assign zext_ln1796_1_fu_2380_p1 = lshr_ln1796_1_fu_2370_p4;

assign zext_ln1796_2_fu_2244_p1 = shl_ln18_fu_2236_p3;

assign zext_ln1796_3_fu_2360_p1 = shl_ln1796_1_fu_2352_p3;

assign zext_ln1796_fu_2264_p1 = lshr_ln18_fu_2254_p4;

assign zext_ln1797_1_fu_2494_p1 = cc_12_reg_653;

assign zext_ln1797_fu_2302_p1 = cc_reg_632;

assign zext_ln1798_1_fu_2519_p1 = add_ln1794_1_fu_2513_p2;

assign zext_ln1798_fu_2327_p1 = add_ln1794_fu_2321_p2;

assign zext_ln1830_1_fu_1996_p1 = shl_ln17_fu_1988_p3;

assign zext_ln1830_fu_2016_p1 = lshr_ln14_fu_2006_p4;

assign zext_ln1831_fu_2037_p1 = lshr_ln15_fu_2027_p4;

assign zext_ln1832_1_fu_2092_p1 = vla1_q0;

assign zext_ln1832_fu_2082_p1 = vla1_q1;

assign zext_ln1835_1_fu_2150_p1 = trunc_ln1835_fu_2146_p1;

assign zext_ln1835_fu_2170_p1 = lshr_ln16_fu_2160_p4;

assign zext_ln1836_1_fu_2179_p1 = trunc_ln1836_fu_2175_p1;

assign zext_ln1836_fu_2199_p1 = lshr_ln17_fu_2189_p4;

assign zext_ln2146_1_fu_1296_p1 = shl_ln_fu_1288_p3;

assign zext_ln2146_fu_1316_p1 = lshr_ln_fu_1306_p4;

assign zext_ln2147_fu_1337_p1 = lshr_ln10_fu_1327_p4;

assign zext_ln2166_1_fu_1520_p1 = a1_2_fu_1472_p2;

assign zext_ln2166_fu_1516_p1 = shl_ln14_fu_1508_p3;

assign zext_ln2167_1_fu_1542_p1 = b1_2_fu_1496_p2;

assign zext_ln2167_fu_1538_p1 = shl_ln15_fu_1530_p3;

assign zext_ln2184_fu_1552_p1 = i_reg_502;

assign zext_ln2241_fu_1870_p1 = lshr_ln12_fu_1860_p4;

assign zext_ln2245_fu_1954_p1 = lshr_ln13_fu_1944_p4;

assign zext_ln2271_1_fu_2560_p1 = shl_ln16_fu_2552_p3;

assign zext_ln2271_fu_2580_p1 = lshr_ln11_fu_2570_p4;

always @ (posedge ap_clk) begin
    tmp_reg_2713[1:0] <= 2'b00;
    tmp_3_reg_2751[1:0] <= 2'b00;
    tmp_8_reg_2815[1:0] <= 2'b00;
    tmp_10_reg_2843[1:0] <= 2'b00;
    zext_ln1830_1_reg_3028[1:0] <= 2'b00;
    zext_ln1830_1_reg_3028[11:9] <= 3'b000;
    select_ln1784_reg_3054[31] <= 1'b0;
    vla1_addr_52_reg_3082[11:10] <= 2'b00;
    select_ln1784_1_reg_3094[31] <= 1'b0;
    vla1_addr_53_reg_3117[11:10] <= 2'b00;
end

endmodule //solve_NTRU_zint_bezout_1
